/**
 * Car advisor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id: number;
    email: string;
    role: UserDto.RoleEnum;
}
export namespace UserDto {
    export type RoleEnum = 'User' | 'Moderator' | 'Admin';
    export const RoleEnum = {
        User: 'User' as RoleEnum,
        Moderator: 'Moderator' as RoleEnum,
        Admin: 'Admin' as RoleEnum
    };
}


