version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/matfij/src/app
      - ./matfij/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - '${PORT}:${PORT}'

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
