/**
 * Car advisor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApproveReportDto } from '../model/models';
import { CreateReportDto } from '../model/models';
import { EstimateDto } from '../model/models';
import { GetEstimateDto } from '../model/models';
import { ReportDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     * @param approveReportDto 
     */
    approveReport(id: string, approveReportDto: ApproveReportDto, extraHttpRequestParams?: any): Observable<ReportDto>;

    /**
     * 
     * 
     * @param createReportDto 
     */
    createReport(createReportDto: CreateReportDto, extraHttpRequestParams?: any): Observable<ReportDto>;

    /**
     * 
     * 
     * @param getEstimateDto 
     */
    getEstimate(getEstimateDto: GetEstimateDto, extraHttpRequestParams?: any): Observable<EstimateDto>;

}
